[keyboard]
name = "rmk-urchin"
product_name = "rmk-urchin"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
board = "nice!nano_v2"

[layout]
rows = 4
cols = 10
map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7) (0,8) (0,9)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7) (1,8) (1,9)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (2,8) (2,9)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6) (3,7) (3,8) (3,9)
"""

[keymap]
layers = 5

[[keymap.layer]] # layer 0
keys = """
Q D R W B J F U P BSLS
A MT(S,LGui) MT(H,LAlt) MT(T,LCtrl) MT(G,LShift) MT(Y,RShift) MT(N,RCtrl) MT(E,RAlt) MT(O,RGui) I
Z X M C V K L COMMA DOT SLASH
_ _ _ LT(2,ENTER) LT(1,TAB) LT(4,SPACE) LT(3,BACKSPACE) _ _ User7
"""

[[keymap.layer]] # layer 1
keys = """
GRAVE _ _ _ _ LEFT DOWN UP RIGHT WM(BSLS,RCtrl)
WM(GRAVE,RShift) LGui LAlt LCtrl LShift 9 1 2 3 4
ESCAPE _ _ _ _ 0 5 6 7 8
_ _ _ _ NO _ _ _ _ _
"""

[[keymap.layer]] # layer 2
keys = """
GRAVE _ _ _ _ _ DELETE PGUP PGDN WM(BSLS,RCtrl)
_ LGui LAlt LCtrl LShift [ MINUS EQUAL ; QUOTE
ESCAPE _ _ _ _ ] SHIFTED(MINUS) SHIFTED(EQUAL) SHIFTED(;) SHIFTED(QUOTE)
_ _ _ _ _ _ _ _ _ _
"""

[[keymap.layer]] # layer 3
keys = """
_ _ _ _ _ MUTE VOLD VOLU MPLY MSTP
_ _ _ _ _ _ _ _ _ _
ESCAPE _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _
"""

[[keymap.layer]] # layer 4
keys = """
_ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _
ESCAPE _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _
"""

[ble]
enabled = true

[split]
connection = "ble"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 5

[split.central.matrix]
row_pins = [
  "P1_13",
  "P1_11",
  "P0_10",
  "P0_09",
]
col_pins = [
  "P0_24",
  "P1_00",
  "P0_11",
  "P1_04",
  "P1_06",
]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 0

[split.peripheral.matrix]
row_pins = [
  "P1_00",
  "P0_11",
  "P1_04",
  "P1_06",
]
col_pins = [
  "P1_15",
  "P1_13",
  "P1_11",
  "P0_10",
  "P0_09",
]

[behavior.morse]
# Hold-priority: modifier wins unless it's a fast clean tap.
enable_flow_tap = false
prior_idle_time = "120ms" # unused while flow tap is off
hold_on_other_press = true
hold_timeout = "150ms"
gap_timeout = "200ms"

[rmk]
split_peripherals_num = 1
ble_profiles_num = 3
debounce_time = 30

[host]
unlock_keys = [[0, 5], [0, 6]]
